### ISSUE TITLE
Document your choice of PCB Components

### ISSUE THREAD

**Issue by McSam27** [FateNozomi/arisu-pcb#1]
Hi, awesome project!! Looking forward to doing this myself.

Do you mind going through and finding links for the PCB components? I'm looking and I came up with a cart all from Mouser and I'm new to this... so just wondering if you could check it over? 

Adding a 'suggested' list of PCB components might be helpful for others to create this keyboard

[arisu_mouser_cart.pdf](https://github.com/FateNozomi/arisu-pcb/files/3366620/arisu_mouser_cart.pdf)

**Comment by FateNozomi** [comment]
I've uploaded an additional BoM with links to the part on mouser under releases [arisu_bom_1.0_Mouser.xlsx](https://github.com/FateNozomi/arisu-pcb/releases/tag/v1.0)
