### ISSUE TITLE
how would we load the keyboard layout on this 

### ISSUE THREAD

**Issue by pookie69** [FateNozomi/arisu-pcb#3]
how would we load the layout onto this. does it use qmk

**Comment by pookie69** [comment]
pls

**Comment by FateNozomi** [comment]
I have a QMK fork with a branch here https://github.com/FateNozomi/qmk_firmware/tree/arisu.
You will have to build it from source. You might need to rebase the branch onto the upstream master as it is quite old.

**Comment by pookie69** [comment]
> I have a QMK fork with a branch here https://github.com/FateNozomi/qmk_firmware/tree/arisu.
> You will have to build it from source. You might need to rebase the branch onto the upstream master as it is quite old.

also is ther a full plate design

**Comment by FateNozomi** [comment]
> > I have a QMK fork with a branch here https://github.com/FateNozomi/qmk_firmware/tree/arisu.
> > You will have to build it from source. You might need to rebase the branch onto the upstream master as it is quite old.
> 
> also is ther a full plate design

https://github.com/FateNozomi/arisu-case

**Comment by hudson-ai** [comment]
The link to the arisu branch of your QMK fork seems to be dead. Is there a different compatible branch? Thanks!

**Comment by FateNozomi** [comment]
@hudson-ai Yes, it was removed because arisu was merged into qmk: https://github.com/qmk/qmk_firmware/tree/master/keyboards/arisu

**Comment by hudson-ai** [comment]
Ah, sweet! Thanks.
